[env]
DEP_LV_CONFIG_PATH={ value="./lv_gtk",relative=true}
LVGL_INCLUDE = """
/usr/include/gtk-3.0,\
/usr/include,\
/usr/local/include,\
/usr/include/glib-2.0,\
/usr/lib/x86_64-linux-gnu/glib-2.0/include,\
/usr/include/pango-1.0,\
/usr/include/harfbuzz,\
/usr/include/cairo,\
/usr/include/gdk-pixbuf-2.0,\
/usr/include/atk-1.0,\
/usr/include/freetype2,\
/opt/homebrew/Cellar/sdl2/2.26.5/include/"""
LVGL_LINK="gtk-3,gdk-3,pangocairo-1.0,pango-1.0,harfbuzz,atk-1.0,cairo-gobject,cairo,gdk_pixbuf-2.0,gio-2.0,gobject-2.0,glib-2.0"
LIBCLANG_PATH={ value = "/usr/lib/llvm-14/lib" ,force=true}
# LIBCLANG_PATH={ value = "/Library/Developer/CommandLineTools/usr/lib/" ,force=true}
# the above path can be obtained with >llvm-config --libdir<  , don't know how to do get the ouput of a command in env var
PKG_CONFIG_SYSROOT_DIR="~/rpi-sysroot"
PKG_CONFIG_ALLOW_CROSS="1"

[build]
target = "x86_64-unknown-linux-gnu"
profile = "release"
opt-level = 3
debug = false

[target.x86_64-unknown-linux-gnu]
rustc-env = {DEP_LV_CONFIG_PATH="./lv_gtk", PKG_CONFIG_ALLOW_CROSS="1",LIBCLANG_PATH="/usr/lib/llvm-14/lib",LVGL_LINK="gtk-3,gdk-3,pangocairo-1.0,pango-1.0,harfbuzz,atk-1.0,cairo-gobject,cairo,gdk_pixbuf-2.0,gio-2.0,gobject-2.0,glib-2.0"}

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-L/opt/homebrew/lib",
    "-C", "link-arg=-lpthread",
    ]
rustc-env = {DEP_LV_CONFIG_PATH="./lv_sdl",PKG_CONFIG_ALLOW_CROSS="1",LIBCLANG_PATH="/Library/Developer/CommandLineTools/usr/lib/",LVGL_LINK="SDL2,SDL"}

# Pi 0/1
[target.arm-unknown-linux-gnueabihf]
rustc-env = {PKG_CONFIG_ALLOW_CROSS="1",LIBCLANG_PATH="/usr/lib/llvm-14/lib",PKG_CONFIG_SYSROOT_DIR="~/rpi-sysroot",DEP_LV_CONFIG_PATH="./lv_fb",CRATE_CC_NO_DEFAULTS="1"} # for lvgl c build 
linker = "arm-linux-gnueabihf-gcc"
rustflags = [
    "-C", "link-arg=--sysroot=/home/lieven/rpi-sysroot",
    "-C", "link-arg=-L/home/lieven/rpi-sysroot/usr/lib/arm-linux-gnueabihf",
    "-C", "link-arg=-L/home/lieven/rpi-sysroot/usr/lib",
    "-C", "link-arg=-L/home/lieven/toolchain/arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/lib",
    "-C", "link-arg=-lpthread",
    ]
# rustc-flags = { sysroot="~/rpi-sysroot" }
# rustc-cfg = ['key="value"']
# rustc-link-lib = ["gtk-3","gdk-3","pangocairo-1.0","pango-1.0","harfbuzz","atk-1.0","cairo-gobject","cairo","gdk_pixbuf-2.0","gio-2.0","gobject-2.0","glib-2.0","SDL2","SDL"]
# rustc-cdylib-link-arg = ["…"]

 
